#server:
#  port: 15262
#  error.whitelabel.enabled: false
#  tomcat:
#    accesslog.enabled: true
#    max-threads: 30
#  servlet.context-path: /devicescacheupdater
    
#logging:
#  level:
#    org.springframework.web: INFO
#    org.hibernate: ERROR
#    es.fermax.logging.aop: DEBUG
#  file: "target/devicecacheupdater-service.log"
server:
  port: 8081
  tomcat:
    max-threads: 30
    accesslog.enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

swagger:
  host: localhost:9999

oauth:
  server: http://localhost:8090/oauth
  sign_token: ${SIGN_TOKEN:this_needs_to_be_the_same_always_and_also_very_cuR3-._}
  client: ${CLIENT:my-client}
  secret: ${SECRET:LHsE2s4mcQ85zgPGoba5SAgH-t0qVSM6Kh6vGuRL50ldtCg7j06dgtKkmjPzCTxXMiMxPjWKS9R6GJxtERMZ3Q}
  username: ${SECRETS_ADMIN_USER:admin}
  password: ${SECRETS_ADMIN_PASS:password}
  server-token: https://localhost:8090/oauth/token

# Specify the DNS URI of your Redis cache.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true

  main:
    allow-bean-definition-overriding: true