
server:
  port: 8081
  tomcat:
    max-threads: 30
    accesslog.enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

oauth:
  server: http://localhost:8090/oauth
  sign_token: ${SIGN_TOKEN:this_needs_to_be_the_same_always_and_also_very_cuR3-._}
  client: ${CLIENT:my-client}
  secret: ${SECRET:LHsE2s4mcQ85zgPGoba5SAgH-t0qVSM6Kh6vGuRL50ldtCg7j06dgtKkmjPzCTxXMiMxPjWKS9R6GJxtERMZ3Q}
  username: ${SECRETS_ADMIN_USER:admin}
  password: ${SECRETS_ADMIN_PASS:password}
  server-token: https://localhost:8090/oauth/token

# Specify the DNS URI of your Redis cache.

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      connection-test-query: SELECT 1
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      use_sql_comments: true

  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    virtual-host: ${RABBIT_VHOST:distribuidos}
    port: 5672
    username: ${RABBITMQ_USER_ROOT:twcam-pls}
    password: ${RABBITMQ_PWD_ROOT:twcam-pls}

rabbitmq:
  exchange_name:
    pago: pago-exchange-distribuidos